const foodData = [
  {
    id: 1,
    name: '鱼香肉丝',
    category: '川菜',
    price: 28,
    introduction: '一道经典的川菜，以猪肉、木耳和胡萝卜为主要食材，口感酸甜。',
    mainIngredients: '猪肉丝, 木耳, 胡萝卜, 青椒',
    cookingTime: '大约30分钟',
    difficulty: '中等',
    calories: '约250卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '无已知过敏原',
    nutritionTips: '含有丰富的蛋白质和维生素',
    imageUrl: 'https://example.com/images/yuxiangrousil.png',
  },
  {
    id: 2,
    name: '宫保鸡丁',
    category: '川菜',
    price: 32,
    introduction: '鸡肉丁与花生米炒制而成，味道麻辣鲜香。',
    mainIngredients: '鸡胸肉, 花生米, 干辣椒, 花椒',
    cookingTime: '大约25分钟',
    difficulty: '简单',
    calories: '约300卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '可能含花生过敏原',
    nutritionTips: '富含蛋白质和微量元素',
    imageUrl: 'https://example.com/images/gongbaojidin.png',
  },
  {
    id: 3,
    name: '麻婆豆腐',
    category: '川菜',
    price: 22,
    introduction: '四川传统名菜之一，以豆腐和牛肉末为主料，味道麻辣。',
    mainIngredients: '嫩豆腐, 牛肉末, 豆瓣酱, 花椒',
    cookingTime: '大约20分钟',
    difficulty: '简单',
    calories: '约180卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '无已知过敏原',
    nutritionTips: '富含植物蛋白和钙质',
    imageUrl: 'https://example.com/images/mapodofu.png',
  },
  {
    id: 4,
    name: '红烧肉',
    category: '湘菜',
    price: 38,
    introduction: '肥而不腻的猪肉块，经过慢炖，色泽红亮，味道醇厚。',
    mainIngredients: '五花肉, 老抽, 生抽, 冰糖',
    cookingTime: '大约1小时',
    difficulty: '中等',
    calories: '约350卡路里',
    servingSize: '每份100克',
    origin: '湖南省',
    allergens: '无已知过敏原',
    nutritionTips: '提供丰富的脂肪和蛋白质',
    imageUrl: 'https://example.com/images/hongshaorou.png',
  },
  {
    id: 5,
    name: '糖醋排骨',
    category: '粤菜',
    price: 42,
    introduction: '外脆里嫩的小排，裹着酸甜可口的糖醋汁。',
    mainIngredients: '猪小排, 白糖, 醋, 生姜',
    cookingTime: '大约1小时15分钟',
    difficulty: '中等',
    calories: '约320卡路里',
    servingSize: '每份100克',
    origin: '广东省',
    allergens: '无已知过敏原',
    nutritionTips: '富含蛋白质和矿物质',
    imageUrl: 'https://example.com/images/tangcukaipai.png',
  },
  {
    id: 6,
    name: '北京烤鸭',
    category: '京菜',
    price: 88,
    introduction: '北京的传统名菜，皮脆肉嫩，搭配葱、黄瓜条和甜面酱食用。',
    mainIngredients: '鸭子, 甜面酱, 葱, 黄瓜条',
    cookingTime: '大约3小时',
    difficulty: '困难',
    calories: '约400卡路里',
    servingSize: '每份100克',
    origin: '北京市',
    allergens: '无已知过敏原',
    nutritionTips: '提供高质量的蛋白质和维生素A',
    imageUrl: 'https://example.com/images/beijingkaoya.png',
  },
  {
    id: 7,
    name: '水煮鱼',
    category: '川菜',
    price: 46,
    introduction: '用草鱼片和大量花椒、干辣椒烹制而成，麻辣鲜香。',
    mainIngredients: '草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '大约45分钟',
    difficulty: '中等',
    calories: '约280卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '无已知过敏原',
    nutritionTips: '富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 8,
    name: '东坡肉',
    category: '浙菜',
    price: 52,
    introduction: '东坡肉东坡肉东坡肉东坡肉',
    mainIngredients: '草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '大约45分钟',
    difficulty: '中等',
    calories: '约280卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '无已知过敏原',
    nutritionTips: '富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 9,
    name: '小笼包',
    category: '苏菜',
    price: 18,
    introduction: '小笼包小笼包小笼包小笼包小笼包小笼包',
    mainIngredients: '草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '大约45分钟',
    difficulty: '中等',
    calories: '约280卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '无已知过敏原',
    nutritionTips: '富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 10,
    name: '蚂蚁上树',
    category: '川菜',
    price: 26,
    introduction: '蚂蚁上树蚂蚁上树蚂蚁上树蚂蚁上树蚂蚁上树',
    mainIngredients: '草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '大约45分钟',
    difficulty: '中等',
    calories: '约280卡路里',
    servingSize: '每份100克',
    origin: '四川省',
    allergens: '无已知过敏原',
    nutritionTips: '富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },

  {
    id: 11,
    name: '1111鱼香肉丝',
    category: '1111川菜',
    price: 28,
    introduction: '1111一道经典的川菜，以猪肉、木耳和胡萝卜为主要食材，口感酸甜。',
    mainIngredients: '1111猪肉丝, 木耳, 胡萝卜, 青椒',
    cookingTime: '1111大约30分钟',
    difficulty: '1111中等',
    calories: '1111约250卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111含有丰富的蛋白质和维生素',
    imageUrl: 'https://example.com/images/yuxiangrousil.png',
  },
  {
    id: 12,
    name: '1111宫保鸡丁',
    category: '1111川菜',
    price: 32,
    introduction: '1111鸡肉丁与花生米炒制而成，味道麻辣鲜香。',
    mainIngredients: '1111鸡胸肉1111, 花生米, 干辣椒, 花椒',
    cookingTime: '1111大约25分钟',
    difficulty: '1111简单',
    calories: '约1111300卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111可能含花生过敏原',
    nutritionTips: '1111富含蛋白质和微量元素',
    imageUrl: 'https://example.com/images/gongbaojidin.png',
  },
  {
    id: 13,
    name: '1111麻婆豆腐',
    category: '1111川菜',
    price: 22,
    introduction: '1111四川传统名菜之一，以豆腐和牛肉末为主料，味道麻辣。',
    mainIngredients: '1111嫩豆腐,1111 牛肉末, 豆瓣酱, 花椒',
    cookingTime: '1111大约20分钟',
    difficulty: '1111简单',
    calories: '约1111180卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111富含植物蛋白和钙质',
    imageUrl: 'https://example.com/images/mapodofu.png',
  },
  {
    id: 14,
    name: '1111红烧肉',
    category: '1111湘菜',
    price: 38,
    introduction: '1111肥而不腻的猪肉块，经过慢炖，色泽红亮，味道醇厚。',
    mainIngredients: '1111五花肉,1111 老抽, 生抽, 冰糖',
    cookingTime: '1111大约1小时',
    difficulty: '1111中等',
    calories: '约3511110卡路里',
    servingSize: '1111每份100克',
    origin: '1111湖南省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111提供丰富的脂肪和蛋白质',
    imageUrl: 'https://example.com/images/hongshaorou.png',
  },
  {
    id: 15,
    name: '1111糖醋排骨',
    category: '1111粤菜',
    price: 42,
    introduction: '1111外脆里嫩的小排，裹着酸甜可口的糖醋汁。',
    mainIngredients: '1111猪小排,1111 白糖, 醋, 生姜',
    cookingTime: '1111大约1小时15分钟',
    difficulty: '1111中等',
    calories: '1111约320卡路里',
    servingSize: '1111每份100克',
    origin: '1111广东省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111富含蛋白质和矿物质',
    imageUrl: 'https://example.com/images/tangcukaipai.png',
  },
  {
    id: 16,
    name: '1111北京烤鸭',
    category: '1111京菜',
    price: 88,
    introduction: '1111北京的传统名菜，皮脆肉嫩，搭配葱、黄瓜条和甜面酱食用。',
    mainIngredients: '1111鸭子, 甜面酱, 葱, 黄瓜条',
    cookingTime: '1111大约3小时',
    difficulty: '1111困难',
    calories: '1111约400卡路里',
    servingSize: '1111每份100克',
    origin: '1111北京市',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111提供高质量的蛋白质和维生素A',
    imageUrl: 'https://example.com/images/beijingkaoya.png',
  },
  {
    id: 17,
    name: '1111水煮鱼',
    category: '1111川菜',
    price: 46,
    introduction: '1111用草鱼片和大量花椒、干辣椒烹制而成，麻辣鲜香。',
    mainIngredients: '1111草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '1111大约45分钟',
    difficulty: '1111中等',
    calories: '1111约280卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 18,
    name: '1111东坡肉',
    category: '1111浙菜',
    price: 52,
    introduction: '1111东坡肉东坡肉东坡肉东坡肉',
    mainIngredients: '1111草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '1111大约45分钟',
    difficulty: '1111中等',
    calories: '约1111280卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 19,
    name: '1111小笼包',
    category: '1111苏菜',
    price: 18,
    introduction: '1111小笼包小笼包小笼包小笼包小笼包小笼包',
    mainIngredients: '1111草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '1111大约45分钟',
    difficulty: '1111中等',
    calories: '1111约280卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 20,
    name: '1111蚂蚁上树',
    category: '1111川菜',
    price: 26,
    introduction: '1111蚂蚁上树蚂蚁上树蚂蚁上树蚂蚁上树蚂蚁上树',
    mainIngredients: '1111草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '1111大约45分钟',
    difficulty: '1111中等',
    calories: '约1111280卡路里',
    servingSize: '1111每份100克',
    origin: '1111四川省',
    allergens: '1111无已知过敏原',
    nutritionTips: '1111富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 21,
    name: '2222鱼香肉丝',
    category: '2222川菜',
    price: 28,
    introduction: '2222一道经典的川菜，以猪肉、木耳和胡萝卜为主要食材，口感酸甜。',
    mainIngredients: '2222猪肉丝, 木耳, 胡萝卜, 青椒',
    cookingTime: '2222大约30分钟',
    difficulty: '2222中等',
    calories: '2222约250卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222含有丰富的蛋白质和维生素',
    imageUrl: 'https://example.com/images/yuxiangrousil.png',
  },
  {
    id: 22,
    name: '2222宫保鸡丁',
    category: '2222川菜',
    price: 32,
    introduction: '2222鸡肉丁与花生米炒制而成，味道麻辣鲜香。',
    mainIngredients: '2222鸡胸肉2222, 花生米, 干辣椒, 花椒',
    cookingTime: '2222大约25分钟',
    difficulty: '2222简单',
    calories: '约2222300卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222可能含花生过敏原',
    nutritionTips: '2222富含蛋白质和微量元素',
    imageUrl: 'https://example.com/images/gongbaojidin.png',
  },
  {
    id: 23,
    name: '2222麻婆豆腐',
    category: '2222川菜',
    price: 22,
    introduction: '2222四川传统名菜之一，以豆腐和牛肉末为主料，味道麻辣。',
    mainIngredients: '2222嫩豆腐,2222 牛肉末, 豆瓣酱, 花椒',
    cookingTime: '2222大约20分钟',
    difficulty: '2222简单',
    calories: '约2222180卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222富含植物蛋白和钙质',
    imageUrl: 'https://example.com/images/mapodofu.png',
  },
  {
    id: 24,
    name: '2222红烧肉',
    category: '2222湘菜',
    price: 38,
    introduction: '2222肥而不腻的猪肉块，经过慢炖，色泽红亮，味道醇厚。',
    mainIngredients: '2222五花肉,2222 老抽, 生抽, 冰糖',
    cookingTime: '2222大约1小时',
    difficulty: '2222中等',
    calories: '约3522220卡路里',
    servingSize: '2222每份100克',
    origin: '2222湖南省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222提供丰富的脂肪和蛋白质',
    imageUrl: 'https://example.com/images/hongshaorou.png',
  },
  {
    id: 25,
    name: '2222糖醋排骨',
    category: '2222粤菜',
    price: 42,
    introduction: '2222外脆里嫩的小排，裹着酸甜可口的糖醋汁。',
    mainIngredients: '2222猪小排,2222 白糖, 醋, 生姜',
    cookingTime: '2222大约1小时15分钟',
    difficulty: '2222中等',
    calories: '2222约320卡路里',
    servingSize: '2222每份100克',
    origin: '2222广东省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222富含蛋白质和矿物质',
    imageUrl: 'https://example.com/images/tangcukaipai.png',
  },
  {
    id: 26,
    name: '2222北京烤鸭',
    category: '2222京菜',
    price: 88,
    introduction: '2222北京的传统名菜，皮脆肉嫩，搭配葱、黄瓜条和甜面酱食用。',
    mainIngredients: '2222鸭子, 甜面酱, 葱, 黄瓜条',
    cookingTime: '2222大约3小时',
    difficulty: '2222困难',
    calories: '2222约400卡路里',
    servingSize: '2222每份100克',
    origin: '2222北京市',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222提供高质量的蛋白质和维生素A',
    imageUrl: 'https://example.com/images/beijingkaoya.png',
  },
  {
    id: 27,
    name: '2222水煮鱼',
    category: '2222川菜',
    price: 46,
    introduction: '2222用草鱼片和大量花椒、干辣椒烹制而成，麻辣鲜香。',
    mainIngredients: '2222草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '2222大约45分钟',
    difficulty: '2222中等',
    calories: '2222约280卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 28,
    name: '2222东坡肉',
    category: '2222浙菜',
    price: 52,
    introduction: '2222东坡肉东坡肉东坡肉东坡肉',
    mainIngredients: '2222草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '2222大约45分钟',
    difficulty: '2222中等',
    calories: '约2222280卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 29,
    name: '2222小笼包',
    category: '2222苏菜',
    price: 18,
    introduction: '2222小笼包小笼包小笼包小笼包小笼包小笼包',
    mainIngredients: '2222草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '2222大约45分钟',
    difficulty: '2222中等',
    calories: '2222约280卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
  {
    id: 30,
    name: '2222蚂蚁上树',
    category: '2222川菜',
    price: 26,
    introduction: '2222蚂蚁上树蚂蚁上树蚂蚁上树蚂蚁上树蚂蚁上树',
    mainIngredients: '2222草鱼, 豆芽, 花椒, 干辣椒',
    cookingTime: '2222大约45分钟',
    difficulty: '2222中等',
    calories: '约2222280卡路里',
    servingSize: '2222每份100克',
    origin: '2222四川省',
    allergens: '2222无已知过敏原',
    nutritionTips: '2222富含蛋白质和不饱和脂肪酸',
    imageUrl: 'https://example.com/images/shuizhuyu.png',
  },
]
class Food {
  async getFoodList(page: number = 1, pageSize: number = 10) {
    const startIndex = (page - 1) * pageSize
    const endIndex = startIndex + pageSize
    const paginatedData = foodData.slice(startIndex, endIndex)

    return {
      data: paginatedData.map((p) => {
        return { id: p.id, name: p.name, category: p.category, price: p.price, difficulty: p.difficulty }
      }),
      pagination: {
        currentPage: page,
        pageSize: pageSize,
        totalItems: foodData.length,
        totalPages: Math.ceil(foodData.length / pageSize),
      },
    }
  }

  async getFoodListById(id: number) {
    return foodData.find((food) => food.id === id)!
  }

  async deleteFood(id: number) {
    const index = foodData.findIndex((food) => food.id === id)
    if (index !== -1) {
      foodData.splice(index, 1)
      return true
    }
    return false
  }

  async updateFood(id: number, updatedFood: any) {
    const index = foodData.findIndex((food) => food.id === id)
    if (index !== -1) {
      foodData[index] = { ...foodData[index], ...updatedFood }
      return true
    }
  }
}
export const mockfood = new Food()
